[project]
name = "osom-regridder"
version = "0.1.0"
description = "Transforms OSOM data from an internal grid system to a lat/lon grid."
readme = "README.md"
dependencies = [
    "netcdf4>=1.7.3",
    "numpy>=2.3.5",
    "pillow>=12.0.0",
]
